model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 28
  loss_fn: 'MSE'
  paths: 20
  beta: 0
  radius: 50
  scale_factor: 1
  learn_sampling: False
  only_auxillary_training: False
  memory_leak_training: False

exp_params:
  dataset: sketchrnn
  data_path: "./data/material_changed_train/"
  img_size: 128
  batch_size: 1 # Better to have a square number
  val_batch_size: 8 # Better to have a square number
  val_shuffle: False
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: False

trainer_params:
  gpus: 1
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VanillaVAE"
  version: 123
  manual_seed: 1265
